version: "3"

services:
  back-end:
    image: nest-dev-backend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./project:/project
    working_dir: /project
    command: ["npm", "run", "start:dev"]
  
  DB:
    image: mariadb:11.3.2
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=db_projet_dev
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=db_projet_dev