version: "3.8"

services:
  site1:
    build:
      context: .
      dockerfile: site1.Dockerfile
    ports:
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:12345:12345"
    command: bash -c "python3 tcp-server-12345.py & npm run dev"